import type { ChordData } from '@/types/chord';

export const CHORDS: ChordData[] = [
  // ========================
  // OPEN MAJOR CHORDS
  // ========================
  {
    id: 'open-c-major',
    name: 'C Major',
    symbol: 'C',
    category: 'open',
    type: 'major',
    frets: [-1, 3, 2, 0, 1, 0],
    fingers: [0, 2, 3, 0, 1, 0],
    baseFret: 1,
    rootNoteString: 1,
  },
  {
    id: 'open-d-major',
    name: 'D Major',
    symbol: 'D',
    category: 'open',
    type: 'major',
    frets: [-1, -1, 0, 2, 3, 2],
    fingers: [0, 0, 0, 1, 3, 2],
    baseFret: 1,
    rootNoteString: 2,
  },
  {
    id: 'open-e-major',
    name: 'E Major',
    symbol: 'E',
    category: 'open',
    type: 'major',
    frets: [0, 2, 2, 1, 0, 0],
    fingers: [0, 2, 1, 3, 0, 0],
    baseFret: 1,
    rootNoteString: 0,
  },
  {
    id: 'open-g-major',
    name: 'G Major',
    symbol: 'G',
    category: 'open',
    type: 'major',
    frets: [3, 2, 0, 0, 3, 3],
    fingers: [2, 1, 0, 0, 3, 4],
    baseFret: 1,
    rootNoteString: 0,
  },
  {
    id: 'open-a-major',
    name: 'A Major',
    symbol: 'A',
    category: 'open',
    type: 'major',
    frets: [-1, 0, 2, 2, 2, 0],
    fingers: [0, 0, 2, 1, 3, 0],
    baseFret: 1,
    rootNoteString: 1,
  },

  // ========================
  // OPEN MINOR CHORDS
  // ========================
  {
    id: 'open-am',
    name: 'A Minor',
    symbol: 'Am',
    category: 'open',
    type: 'minor',
    frets: [-1, 0, 2, 2, 1, 0],
    fingers: [0, 0, 2, 3, 1, 0],
    baseFret: 1,
    rootNoteString: 1,
  },
  {
    id: 'open-dm',
    name: 'D Minor',
    symbol: 'Dm',
    category: 'open',
    type: 'minor',
    frets: [-1, -1, 0, 2, 3, 1],
    fingers: [0, 0, 0, 2, 3, 1],
    baseFret: 1,
    rootNoteString: 2,
  },
  {
    id: 'open-em',
    name: 'E Minor',
    symbol: 'Em',
    category: 'open',
    type: 'minor',
    frets: [0, 2, 2, 0, 0, 0],
    fingers: [0, 1, 2, 0, 0, 0],
    baseFret: 1,
    rootNoteString: 0,
  },

  // ========================
  // OPEN DOMINANT 7TH CHORDS
  // ========================
  {
    id: 'open-a7',
    name: 'A Dominant 7th',
    symbol: 'A7',
    category: 'open',
    type: 'dominant7',
    frets: [-1, 0, 2, 0, 2, 0],
    fingers: [0, 0, 2, 0, 3, 0],
    baseFret: 1,
    rootNoteString: 1,
  },
  {
    id: 'open-b7',
    name: 'B Dominant 7th',
    symbol: 'B7',
    category: 'open',
    type: 'dominant7',
    frets: [-1, 2, 1, 2, 0, 2],
    fingers: [0, 2, 1, 3, 0, 4],
    baseFret: 1,
    rootNoteString: 1,
  },
  {
    id: 'open-c7',
    name: 'C Dominant 7th',
    symbol: 'C7',
    category: 'open',
    type: 'dominant7',
    frets: [-1, 3, 2, 3, 1, 0],
    fingers: [0, 3, 2, 4, 1, 0],
    baseFret: 1,
    rootNoteString: 1,
  },
  {
    id: 'open-d7',
    name: 'D Dominant 7th',
    symbol: 'D7',
    category: 'open',
    type: 'dominant7',
    frets: [-1, -1, 0, 2, 1, 2],
    fingers: [0, 0, 0, 2, 1, 3],
    baseFret: 1,
    rootNoteString: 2,
  },
  {
    id: 'open-e7',
    name: 'E Dominant 7th',
    symbol: 'E7',
    category: 'open',
    type: 'dominant7',
    frets: [0, 2, 0, 1, 0, 0],
    fingers: [0, 2, 0, 1, 0, 0],
    baseFret: 1,
    rootNoteString: 0,
  },
  {
    id: 'open-g7',
    name: 'G Dominant 7th',
    symbol: 'G7',
    category: 'open',
    type: 'dominant7',
    frets: [3, 2, 0, 0, 0, 1],
    fingers: [3, 2, 0, 0, 0, 1],
    baseFret: 1,
    rootNoteString: 0,
  },

  // ========================
  // OPEN MAJOR 7TH CHORDS
  // ========================
  {
    id: 'open-cmaj7',
    name: 'C Major 7th',
    symbol: 'Cmaj7',
    category: 'open',
    type: 'major7',
    frets: [-1, 3, 2, 0, 0, 0],
    fingers: [0, 3, 2, 0, 0, 0],
    baseFret: 1,
    rootNoteString: 1,
  },
  {
    id: 'open-dmaj7',
    name: 'D Major 7th',
    symbol: 'Dmaj7',
    category: 'open',
    type: 'major7',
    frets: [-1, -1, 0, 2, 2, 2],
    fingers: [0, 0, 0, 1, 1, 1],
    baseFret: 1,
    rootNoteString: 2,
  },
  {
    id: 'open-emaj7',
    name: 'E Major 7th',
    symbol: 'Emaj7',
    category: 'open',
    type: 'major7',
    frets: [0, 2, 1, 1, 0, 0],
    fingers: [0, 3, 1, 2, 0, 0],
    baseFret: 1,
    rootNoteString: 0,
  },
  {
    id: 'open-fmaj7',
    name: 'F Major 7th',
    symbol: 'Fmaj7',
    category: 'open',
    type: 'major7',
    frets: [-1, -1, 3, 2, 1, 0],
    fingers: [0, 0, 3, 2, 1, 0],
    baseFret: 1,
    rootNoteString: 2,
  },
  {
    id: 'open-gmaj7',
    name: 'G Major 7th',
    symbol: 'Gmaj7',
    category: 'open',
    type: 'major7',
    frets: [3, 2, 0, 0, 0, 2],
    fingers: [2, 1, 0, 0, 0, 3],
    baseFret: 1,
    rootNoteString: 0,
  },
  {
    id: 'open-amaj7',
    name: 'A Major 7th',
    symbol: 'Amaj7',
    category: 'open',
    type: 'major7',
    frets: [-1, 0, 2, 1, 2, 0],
    fingers: [0, 0, 2, 1, 3, 0],
    baseFret: 1,
    rootNoteString: 1,
  },

  // ========================
  // OPEN MINOR 7TH CHORDS
  // ========================
  {
    id: 'open-bm7',
    name: 'B Minor 7th',
    symbol: 'Bm7',
    category: 'open',
    type: 'minor7',
    frets: [-1, 2, 0, 2, 0, 2],
    fingers: [0, 2, 0, 3, 0, 4],
    baseFret: 1,
    rootNoteString: 1,
  },
  {
    id: 'open-am7',
    name: 'A Minor 7th',
    symbol: 'Am7',
    category: 'open',
    type: 'minor7',
    frets: [-1, 0, 2, 0, 1, 0],
    fingers: [0, 0, 2, 0, 1, 0],
    baseFret: 1,
    rootNoteString: 1,
  },
  {
    id: 'open-dm7',
    name: 'D Minor 7th',
    symbol: 'Dm7',
    category: 'open',
    type: 'minor7',
    frets: [-1, -1, 0, 2, 1, 1],
    fingers: [0, 0, 0, 2, 1, 1],
    baseFret: 1,
    rootNoteString: 2,
  },
  {
    id: 'open-em7',
    name: 'E Minor 7th',
    symbol: 'Em7',
    category: 'open',
    type: 'minor7',
    frets: [0, 2, 2, 0, 3, 0],
    fingers: [0, 1, 2, 0, 3, 0],
    baseFret: 1,
    rootNoteString: 0,
  },

  // ========================
  // OPEN SUSPENDED CHORDS
  // ========================
  {
    id: 'open-asus2',
    name: 'A Suspended 2nd',
    symbol: 'Asus2',
    category: 'open',
    type: 'suspended',
    frets: [-1, 0, 2, 2, 0, 0],
    fingers: [0, 0, 1, 2, 0, 0],
    baseFret: 1,
    rootNoteString: 1,
  },
  {
    id: 'open-asus4',
    name: 'A Suspended 4th',
    symbol: 'Asus4',
    category: 'open',
    type: 'suspended',
    frets: [-1, 0, 2, 2, 3, 0],
    fingers: [0, 0, 1, 2, 3, 0],
    baseFret: 1,
    rootNoteString: 1,
  },
  {
    id: 'open-dsus2',
    name: 'D Suspended 2nd',
    symbol: 'Dsus2',
    category: 'open',
    type: 'suspended',
    frets: [-1, -1, 0, 2, 3, 0],
    fingers: [0, 0, 0, 1, 3, 0],
    baseFret: 1,
    rootNoteString: 2,
  },
  {
    id: 'open-dsus4',
    name: 'D Suspended 4th',
    symbol: 'Dsus4',
    category: 'open',
    type: 'suspended',
    frets: [-1, -1, 0, 2, 3, 3],
    fingers: [0, 0, 0, 1, 2, 3],
    baseFret: 1,
    rootNoteString: 2,
  },
  {
    id: 'open-esus4',
    name: 'E Suspended 4th',
    symbol: 'Esus4',
    category: 'open',
    type: 'suspended',
    frets: [0, 2, 2, 2, 0, 0],
    fingers: [0, 2, 3, 4, 0, 0],
    baseFret: 1,
    rootNoteString: 0,
  },

  // ========================
  // OPEN AUGMENTED CHORDS
  // ========================
  {
    id: 'open-caug',
    name: 'C Augmented',
    symbol: 'C+',
    category: 'open',
    type: 'augmented',
    frets: [-1, 3, 2, 1, 1, 0],
    fingers: [0, 4, 3, 1, 2, 0],
    baseFret: 1,
    rootNoteString: 1,
  },
  {
    id: 'open-eaug',
    name: 'E Augmented',
    symbol: 'E+',
    category: 'open',
    type: 'augmented',
    frets: [0, 3, 2, 1, 1, 0],
    fingers: [0, 4, 3, 2, 1, 0],
    baseFret: 1,
    rootNoteString: 0,
  },
  {
    id: 'open-gaug',
    name: 'G Augmented',
    symbol: 'G+',
    category: 'open',
    type: 'augmented',
    frets: [3, 2, 1, 0, 0, 3],
    fingers: [3, 2, 1, 0, 0, 4],
    baseFret: 1,
    rootNoteString: 0,
  },

  // ========================
  // OPEN DIMINISHED CHORDS
  // ========================
  {
    id: 'open-bdim',
    name: 'B Diminished',
    symbol: 'B°',
    category: 'open',
    type: 'diminished',
    frets: [-1, 2, 3, 4, 3, -1],
    fingers: [0, 1, 2, 4, 3, 0],
    baseFret: 1,
    rootNoteString: 1,
  },
  {
    id: 'open-edim',
    name: 'E Diminished',
    symbol: 'E°',
    category: 'open',
    type: 'diminished',
    frets: [0, 1, 2, 0, 2, 0],
    fingers: [0, 1, 2, 0, 3, 0],
    baseFret: 1,
    rootNoteString: 0,
  },

  // ========================
  // OPEN SLASH CHORDS
  // ========================
  {
    id: 'open-c-g',
    name: 'C over G',
    symbol: 'C/G',
    category: 'open',
    type: 'slash',
    frets: [3, 3, 2, 0, 1, 0],
    fingers: [3, 4, 2, 0, 1, 0],
    baseFret: 1,
    rootNoteString: 0,
  },
  {
    id: 'open-d-fsharp',
    name: 'D over F#',
    symbol: 'D/F#',
    category: 'open',
    type: 'slash',
    frets: [2, -1, 0, 2, 3, 2],
    fingers: [1, 0, 0, 2, 4, 3],
    baseFret: 1,
    rootNoteString: 0,
  },
  {
    id: 'open-am-e',
    name: 'Am over E',
    symbol: 'Am/E',
    category: 'open',
    type: 'slash',
    frets: [0, 0, 2, 2, 1, 0],
    fingers: [0, 0, 2, 3, 1, 0],
    baseFret: 1,
    rootNoteString: 0,
  },
  {
    id: 'open-g-b',
    name: 'G over B',
    symbol: 'G/B',
    category: 'open',
    type: 'slash',
    frets: [-1, 2, 0, 0, 0, 3],
    fingers: [0, 1, 0, 0, 0, 3],
    baseFret: 1,
    rootNoteString: 1,
  },

  // ========================
  // OPEN 9TH CHORDS
  // ========================
  {
    id: 'open-a9',
    name: 'A 9th',
    symbol: 'A9',
    category: 'open',
    type: '9th',
    frets: [-1, 0, 2, 4, 2, 3],
    fingers: [0, 0, 1, 3, 1, 2],
    baseFret: 1,
    rootNoteString: 1,
  },
  {
    id: 'open-e9',
    name: 'E 9th',
    symbol: 'E9',
    category: 'open',
    type: '9th',
    frets: [0, 2, 0, 1, 0, 2],
    fingers: [0, 2, 0, 1, 0, 3],
    baseFret: 1,
    rootNoteString: 0,
  },
  {
    id: 'open-g9',
    name: 'G 9th',
    symbol: 'G9',
    category: 'open',
    type: '9th',
    frets: [3, -1, 0, 2, 0, 1],
    fingers: [3, 0, 0, 2, 0, 1],
    baseFret: 1,
    rootNoteString: 0,
  },

  // ========================
  // OPEN AUGMENTED 7TH CHORDS
  // ========================
  {
    id: 'open-c-aug7',
    name: 'C Augmented 7th',
    symbol: 'C+7',
    category: 'open',
    type: 'aug7',
    frets: [-1, 3, 2, 1, 1, 2],
    fingers: [0, 4, 3, 1, 1, 2],
    baseFret: 1,
    rootNoteString: 1,
  },
  {
    id: 'open-e-aug7',
    name: 'E Augmented 7th',
    symbol: 'E+7',
    category: 'open',
    type: 'aug7',
    frets: [0, 3, 0, 1, 1, 0],
    fingers: [0, 4, 0, 2, 1, 0],
    baseFret: 1,
    rootNoteString: 0,
  },
  {
    id: 'open-g-aug7',
    name: 'G Augmented 7th',
    symbol: 'G+7',
    category: 'open',
    type: 'aug7',
    frets: [3, 2, 1, 0, 0, 1],
    fingers: [3, 2, 1, 0, 0, 1],
    baseFret: 1,
    rootNoteString: 0,
  },
  {
    id: 'open-a-aug7',
    name: 'A Augmented 7th',
    symbol: 'A+7',
    category: 'open',
    type: 'aug7',
    frets: [-1, 0, 3, 0, 2, 1],
    fingers: [0, 0, 4, 0, 2, 1],
    baseFret: 1,
    rootNoteString: 1,
  },

  // ========================
  // OPEN HALF DIMINISHED 7TH CHORDS
  // ========================
  {
    id: 'open-b-halfdim7',
    name: 'B Half Diminished 7th',
    symbol: 'Bm7b5',
    category: 'open',
    type: 'halfDim7',
    frets: [-1, 2, 3, 2, 3, 2],
    fingers: [0, 1, 2, 1, 3, 1],
    baseFret: 1,
    barres: [2],
    rootNoteString: 1,
  },
  {
    id: 'open-d-halfdim7',
    name: 'D Half Diminished 7th',
    symbol: 'Dm7b5',
    category: 'open',
    type: 'halfDim7',
    frets: [-1, -1, 0, 1, 1, 1],
    fingers: [0, 0, 0, 1, 2, 3],
    baseFret: 1,
    rootNoteString: 2,
  },
  {
    id: 'open-e-halfdim7',
    name: 'E Half Diminished 7th',
    symbol: 'Em7b5',
    category: 'open',
    type: 'halfDim7',
    frets: [0, 1, 2, 0, 3, 0],
    fingers: [0, 1, 2, 0, 3, 0],
    baseFret: 1,
    rootNoteString: 0,
  },
  {
    id: 'open-f-halfdim7',
    name: 'F# Half Diminished 7th',
    symbol: 'F#m7b5',
    category: 'open',
    type: 'halfDim7',
    frets: [2, -1, 2, 2, 1, -1],
    fingers: [2, 0, 3, 4, 1, 0],
    baseFret: 1,
    rootNoteString: 0,
  },

  // ========================
  // OPEN FULLY DIMINISHED 7TH CHORDS
  // ========================
  {
    id: 'open-b-dim7',
    name: 'B Fully Diminished 7th',
    symbol: 'Bdim7',
    category: 'open',
    type: 'dim7',
    frets: [-1, 2, 3, 1, 3, 1],
    fingers: [0, 2, 3, 1, 4, 1],
    baseFret: 1,
    rootNoteString: 1,
  },
  {
    id: 'open-c-dim7',
    name: 'C Fully Diminished 7th',
    symbol: 'Cdim7',
    category: 'open',
    type: 'dim7',
    frets: [-1, 3, 4, 2, 4, 2],
    fingers: [0, 2, 3, 1, 4, 1],
    baseFret: 1,
    rootNoteString: 1,
  },
  {
    id: 'open-e-dim7',
    name: 'E Fully Diminished 7th',
    symbol: 'Edim7',
    category: 'open',
    type: 'dim7',
    frets: [0, 1, 2, 0, 2, 0],
    fingers: [0, 1, 2, 0, 3, 0],
    baseFret: 1,
    rootNoteString: 0,
  },

  // ========================
  // BARRE MAJOR CHORDS
  // ========================
  {
    id: 'barre-f-major',
    name: 'F Major',
    symbol: 'F',
    category: 'barre',
    type: 'major',
    frets: [1, 3, 3, 2, 1, 1],
    fingers: [1, 3, 4, 2, 1, 1],
    baseFret: 1,
    barres: [1],
    rootString: 6,
    rootNoteString: 0,
  },
  {
    id: 'barre-bb-major',
    name: 'Bb Major',
    symbol: 'Bb',
    category: 'barre',
    type: 'major',
    frets: [-1, 1, 3, 3, 3, 1],
    fingers: [0, 1, 2, 3, 4, 1],
    baseFret: 1,
    barres: [1],
    rootString: 5,
    rootNoteString: 1,
  },
  {
    id: 'barre-b-major',
    name: 'B Major',
    symbol: 'B',
    category: 'barre',
    type: 'major',
    frets: [-1, 2, 4, 4, 4, 2],
    fingers: [0, 1, 2, 3, 4, 1],
    baseFret: 1,
    barres: [2],
    rootString: 5,
    rootNoteString: 1,
  },
  {
    id: 'barre-ab-major',
    name: 'Ab Major',
    symbol: 'Ab',
    category: 'barre',
    type: 'major',
    frets: [4, 6, 6, 5, 4, 4],
    fingers: [1, 3, 4, 2, 1, 1],
    baseFret: 4,
    barres: [4],
    rootString: 6,
    rootNoteString: 0,
  },
  {
    id: 'barre-eb-major',
    name: 'Eb Major',
    symbol: 'Eb',
    category: 'barre',
    type: 'major',
    frets: [-1, 6, 8, 8, 8, 6],
    fingers: [0, 1, 2, 3, 4, 1],
    baseFret: 6,
    barres: [6],
    rootString: 5,
    rootNoteString: 1,
  },

  // ========================
  // BARRE MINOR CHORDS
  // ========================
  {
    id: 'barre-fm',
    name: 'F Minor',
    symbol: 'Fm',
    category: 'barre',
    type: 'minor',
    frets: [1, 3, 3, 1, 1, 1],
    fingers: [1, 3, 4, 1, 1, 1],
    baseFret: 1,
    barres: [1],
    rootString: 6,
    rootNoteString: 0,
  },
  {
    id: 'barre-fsharp-m',
    name: 'F# Minor',
    symbol: 'F#m',
    category: 'barre',
    type: 'minor',
    frets: [2, 4, 4, 2, 2, 2],
    fingers: [1, 3, 4, 1, 1, 1],
    baseFret: 2,
    barres: [2],
    rootString: 6,
    rootNoteString: 0,
  },
  {
    id: 'barre-bm',
    name: 'B Minor',
    symbol: 'Bm',
    category: 'barre',
    type: 'minor',
    frets: [-1, 2, 4, 4, 3, 2],
    fingers: [0, 1, 3, 4, 2, 1],
    baseFret: 2,
    barres: [2],
    rootString: 5,
    rootNoteString: 1,
  },
  {
    id: 'barre-bbm',
    name: 'Bb Minor',
    symbol: 'Bbm',
    category: 'barre',
    type: 'minor',
    frets: [-1, 1, 3, 3, 2, 1],
    fingers: [0, 1, 3, 4, 2, 1],
    baseFret: 1,
    barres: [1],
    rootString: 5,
    rootNoteString: 1,
  },
  {
    id: 'barre-cm',
    name: 'C Minor',
    symbol: 'Cm',
    category: 'barre',
    type: 'minor',
    frets: [-1, 3, 5, 5, 4, 3],
    fingers: [0, 1, 3, 4, 2, 1],
    baseFret: 3,
    barres: [3],
    rootString: 5,
    rootNoteString: 1,
  },
  {
    id: 'barre-gm',
    name: 'G Minor',
    symbol: 'Gm',
    category: 'barre',
    type: 'minor',
    frets: [3, 5, 5, 3, 3, 3],
    fingers: [1, 3, 4, 1, 1, 1],
    baseFret: 3,
    barres: [3],
    rootString: 6,
    rootNoteString: 0,
  },

  // ========================
  // BARRE DOMINANT 7TH
  // ========================
  {
    id: 'barre-f7',
    name: 'F Dominant 7th',
    symbol: 'F7',
    category: 'barre',
    type: 'dominant7',
    frets: [1, 3, 1, 2, 1, 1],
    fingers: [1, 3, 1, 2, 1, 1],
    baseFret: 1,
    barres: [1],
    rootString: 6,
    rootNoteString: 0,
  },
  {
    id: 'barre-bb7',
    name: 'Bb Dominant 7th',
    symbol: 'Bb7',
    category: 'barre',
    type: 'dominant7',
    frets: [-1, 1, 3, 1, 3, 1],
    fingers: [0, 1, 3, 1, 4, 1],
    baseFret: 1,
    barres: [1],
    rootString: 5,
    rootNoteString: 1,
  },
  {
    id: 'barre-c7-barre',
    name: 'C Dominant 7th',
    symbol: 'C7',
    category: 'barre',
    type: 'dominant7',
    frets: [-1, 3, 5, 3, 5, 3],
    fingers: [0, 1, 3, 1, 4, 1],
    baseFret: 3,
    barres: [3],
    rootString: 5,
    rootNoteString: 1,
  },

  // ========================
  // BARRE MAJOR 7TH
  // ========================
  {
    id: 'barre-fmaj7',
    name: 'F Major 7th',
    symbol: 'Fmaj7',
    category: 'barre',
    type: 'major7',
    frets: [1, -1, 2, 2, 1, -1],
    fingers: [1, 0, 3, 4, 2, 0],
    baseFret: 1,
    rootString: 6,
    rootNoteString: 0,
  },
  {
    id: 'barre-bbmaj7',
    name: 'Bb Major 7th',
    symbol: 'Bbmaj7',
    category: 'barre',
    type: 'major7',
    frets: [-1, 1, 3, 2, 3, 1],
    fingers: [0, 1, 3, 2, 4, 1],
    baseFret: 1,
    barres: [1],
    rootString: 5,
    rootNoteString: 1,
  },

  // ========================
  // BARRE MINOR 7TH
  // ========================
  {
    id: 'barre-fm7',
    name: 'F Minor 7th',
    symbol: 'Fm7',
    category: 'barre',
    type: 'minor7',
    frets: [1, 3, 1, 1, 1, 1],
    fingers: [1, 3, 1, 1, 1, 1],
    baseFret: 1,
    barres: [1],
    rootString: 6,
    rootNoteString: 0,
  },
  {
    id: 'barre-bm7',
    name: 'B Minor 7th',
    symbol: 'Bm7',
    category: 'barre',
    type: 'minor7',
    frets: [-1, 2, 4, 2, 3, 2],
    fingers: [0, 1, 3, 1, 2, 1],
    baseFret: 2,
    barres: [2],
    rootString: 5,
    rootNoteString: 1,
  },
  {
    id: 'barre-cm7',
    name: 'C Minor 7th',
    symbol: 'Cm7',
    category: 'barre',
    type: 'minor7',
    frets: [-1, 3, 5, 3, 4, 3],
    fingers: [0, 1, 3, 1, 2, 1],
    baseFret: 3,
    barres: [3],
    rootString: 5,
    rootNoteString: 1,
  },

  // ========================
  // BARRE SUSPENDED
  // ========================
  {
    id: 'barre-fsus4',
    name: 'F Suspended 4th',
    symbol: 'Fsus4',
    category: 'barre',
    type: 'suspended',
    frets: [1, 3, 3, 3, 1, 1],
    fingers: [1, 2, 3, 4, 1, 1],
    baseFret: 1,
    barres: [1],
    rootString: 6,
    rootNoteString: 0,
  },
  {
    id: 'barre-bsus4',
    name: 'B Suspended 4th',
    symbol: 'Bsus4',
    category: 'barre',
    type: 'suspended',
    frets: [-1, 2, 4, 4, 5, 2],
    fingers: [0, 1, 2, 3, 4, 1],
    baseFret: 2,
    barres: [2],
    rootString: 5,
    rootNoteString: 1,
  },

  // ========================
  // BARRE AUGMENTED
  // ========================
  {
    id: 'barre-faug',
    name: 'F Augmented',
    symbol: 'F+',
    category: 'barre',
    type: 'augmented',
    frets: [1, -1, 3, 2, 2, 1],
    fingers: [1, 0, 4, 2, 3, 1],
    baseFret: 1,
    barres: [1],
    rootString: 6,
    rootNoteString: 0,
  },
  {
    id: 'barre-bbaug',
    name: 'Bb Augmented',
    symbol: 'Bb+',
    category: 'barre',
    type: 'augmented',
    frets: [-1, 1, 4, 3, 3, 2],
    fingers: [0, 1, 4, 2, 3, 1],
    baseFret: 1,
    rootString: 5,
    rootNoteString: 1,
  },

  // ========================
  // BARRE DIMINISHED
  // ========================
  {
    id: 'barre-fdim',
    name: 'F Diminished',
    symbol: 'F°',
    category: 'barre',
    type: 'diminished',
    frets: [1, -1, 3, 1, 0, 1],
    fingers: [1, 0, 4, 2, 0, 3],
    baseFret: 1,
    rootString: 6,
    rootNoteString: 0,
  },

  // ========================
  // BARRE SLASH
  // ========================
  {
    id: 'barre-f-a',
    name: 'F over A',
    symbol: 'F/A',
    category: 'barre',
    type: 'slash',
    frets: [-1, 0, 3, 2, 1, 1],
    fingers: [0, 0, 4, 3, 1, 1],
    baseFret: 1,
    barres: [1],
    rootString: 5,
    rootNoteString: 1,
  },
  {
    id: 'barre-bb-d',
    name: 'Bb over D',
    symbol: 'Bb/D',
    category: 'barre',
    type: 'slash',
    frets: [-1, -1, 0, 3, 3, 1],
    fingers: [0, 0, 0, 2, 3, 1],
    baseFret: 1,
    rootString: 4,
    rootNoteString: 2,
  },

  // ========================
  // BARRE 9TH
  // ========================
  {
    id: 'barre-f9',
    name: 'F 9th',
    symbol: 'F9',
    category: 'barre',
    type: '9th',
    frets: [1, 3, 1, 2, 1, 3],
    fingers: [1, 3, 1, 2, 1, 4],
    baseFret: 1,
    barres: [1],
    rootString: 6,
    rootNoteString: 0,
  },

  // ========================
  // BARRE AUGMENTED 7TH
  // ========================
  {
    id: 'barre-f-aug7',
    name: 'F Augmented 7th',
    symbol: 'F+7',
    category: 'barre',
    type: 'aug7',
    frets: [1, -1, 1, 2, 2, 1],
    fingers: [1, 0, 1, 2, 3, 1],
    baseFret: 1,
    barres: [1],
    rootString: 6,
    rootNoteString: 0,
  },
  {
    id: 'barre-bb-aug7',
    name: 'Bb Augmented 7th',
    symbol: 'Bb+7',
    category: 'barre',
    type: 'aug7',
    frets: [-1, 1, 4, 1, 3, 2],
    fingers: [0, 1, 4, 1, 3, 2],
    baseFret: 1,
    barres: [1],
    rootString: 5,
    rootNoteString: 1,
  },

  // ========================
  // BARRE HALF DIMINISHED 7TH
  // ========================
  {
    id: 'barre-f-halfdim7',
    name: 'F Half Diminished 7th',
    symbol: 'Fm7b5',
    category: 'barre',
    type: 'halfDim7',
    frets: [1, -1, 1, 1, 0, -1],
    fingers: [1, 0, 2, 3, 0, 0],
    baseFret: 1,
    rootString: 6,
    rootNoteString: 0,
  },
  {
    id: 'barre-bb-halfdim7',
    name: 'Bb Half Diminished 7th',
    symbol: 'Bbm7b5',
    category: 'barre',
    type: 'halfDim7',
    frets: [-1, 1, 2, 1, 2, -1],
    fingers: [0, 1, 2, 1, 3, 0],
    baseFret: 1,
    barres: [1],
    rootString: 5,
    rootNoteString: 1,
  },
  {
    id: 'barre-c-halfdim7',
    name: 'C# Half Diminished 7th',
    symbol: 'C#m7b5',
    category: 'barre',
    type: 'halfDim7',
    frets: [-1, 4, 5, 4, 5, -1],
    fingers: [0, 1, 2, 1, 3, 0],
    baseFret: 4,
    barres: [4],
    rootString: 5,
    rootNoteString: 1,
  },

  // ========================
  // BARRE FULLY DIMINISHED 7TH
  // ========================
  {
    id: 'barre-f-dim7',
    name: 'F Fully Diminished 7th',
    symbol: 'Fdim7',
    category: 'barre',
    type: 'dim7',
    frets: [1, -1, 0, 1, 0, 1],
    fingers: [1, 0, 0, 2, 0, 3],
    baseFret: 1,
    rootString: 6,
    rootNoteString: 0,
  },
  {
    id: 'barre-ab-dim7',
    name: 'Ab Fully Diminished 7th',
    symbol: 'Abdim7',
    category: 'barre',
    type: 'dim7',
    frets: [4, -1, 3, 4, 3, 4],
    fingers: [2, 0, 1, 3, 1, 4],
    baseFret: 3,
    rootString: 6,
    rootNoteString: 0,
  },
  {
    id: 'barre-bb-dim7',
    name: 'Bb Fully Diminished 7th',
    symbol: 'Bbdim7',
    category: 'barre',
    type: 'dim7',
    frets: [-1, 1, 2, 0, 2, 0],
    fingers: [0, 1, 2, 0, 3, 0],
    baseFret: 1,
    rootString: 5,
    rootNoteString: 1,
  },

  // ========================
  // MOVABLE MAJOR CHORDS
  // ========================
  {
    id: 'mov-c-major-5th',
    name: 'C Major (5th pos)',
    symbol: 'C',
    category: 'movable',
    type: 'major',
    frets: [-1, 3, 5, 5, 5, 3],
    fingers: [0, 1, 2, 3, 4, 1],
    baseFret: 3,
    rootString: 5,
    rootNoteString: 1,
  },
  {
    id: 'mov-d-major-5th',
    name: 'D Major (5th pos)',
    symbol: 'D',
    category: 'movable',
    type: 'major',
    frets: [-1, 5, 7, 7, 7, 5],
    fingers: [0, 1, 2, 3, 4, 1],
    baseFret: 5,
    rootString: 5,
    rootNoteString: 1,
  },

  // ========================
  // MOVABLE MINOR CHORDS
  // ========================
  {
    id: 'mov-cm-3rd',
    name: 'C Minor (3rd pos)',
    symbol: 'Cm',
    category: 'movable',
    type: 'minor',
    frets: [-1, 3, 5, 5, 4, 3],
    fingers: [0, 1, 3, 4, 2, 1],
    baseFret: 3,
    rootString: 5,
    rootNoteString: 1,
  },
  {
    id: 'mov-gsharp-m',
    name: 'G# Minor',
    symbol: 'G#m',
    category: 'movable',
    type: 'minor',
    frets: [4, 6, 6, 4, 4, 4],
    fingers: [1, 3, 4, 1, 1, 1],
    baseFret: 4,
    rootString: 6,
    rootNoteString: 0,
  },

  // ========================
  // MOVABLE DOMINANT 7TH
  // ========================
  {
    id: 'mov-a7-5th',
    name: 'A Dominant 7th (5th pos)',
    symbol: 'A7',
    category: 'movable',
    type: 'dominant7',
    frets: [5, 7, 5, 6, 5, 5],
    fingers: [1, 3, 1, 2, 1, 1],
    baseFret: 5,
    rootString: 6,
    rootNoteString: 0,
  },
  {
    id: 'mov-d7-5th',
    name: 'D Dominant 7th (5th pos)',
    symbol: 'D7',
    category: 'movable',
    type: 'dominant7',
    frets: [-1, 5, 7, 5, 7, 5],
    fingers: [0, 1, 3, 1, 4, 1],
    baseFret: 5,
    rootString: 5,
    rootNoteString: 1,
  },

  // ========================
  // MOVABLE MAJOR 7TH
  // ========================
  {
    id: 'mov-amaj7',
    name: 'A Major 7th (5th pos)',
    symbol: 'Amaj7',
    category: 'movable',
    type: 'major7',
    frets: [5, -1, 6, 6, 5, 4],
    fingers: [2, 0, 3, 4, 1, 1],
    baseFret: 4,
    rootString: 6,
    rootNoteString: 0,
  },
  {
    id: 'mov-cmaj7-3rd',
    name: 'C Major 7th (3rd pos)',
    symbol: 'Cmaj7',
    category: 'movable',
    type: 'major7',
    frets: [-1, 3, 5, 4, 5, 3],
    fingers: [0, 1, 3, 2, 4, 1],
    baseFret: 3,
    rootString: 5,
    rootNoteString: 1,
  },

  // ========================
  // MOVABLE MINOR 7TH
  // ========================
  {
    id: 'mov-am7-5th',
    name: 'A Minor 7th (5th pos)',
    symbol: 'Am7',
    category: 'movable',
    type: 'minor7',
    frets: [5, 7, 5, 5, 5, 5],
    fingers: [1, 3, 1, 1, 1, 1],
    baseFret: 5,
    rootString: 6,
    rootNoteString: 0,
  },
  {
    id: 'mov-dm7-5th',
    name: 'D Minor 7th (5th pos)',
    symbol: 'Dm7',
    category: 'movable',
    type: 'minor7',
    frets: [-1, 5, 7, 5, 6, 5],
    fingers: [0, 1, 3, 1, 2, 1],
    baseFret: 5,
    rootString: 5,
    rootNoteString: 1,
  },

  // ========================
  // MOVABLE 9TH CHORDS
  // ========================
  {
    id: 'mov-c9',
    name: 'C 9th',
    symbol: 'C9',
    category: 'movable',
    type: '9th',
    frets: [-1, 3, 2, 3, 3, 3],
    fingers: [0, 2, 1, 3, 3, 3],
    baseFret: 2,
    rootString: 5,
    rootNoteString: 1,
  },
  {
    id: 'mov-d9',
    name: 'D 9th',
    symbol: 'D9',
    category: 'movable',
    type: '9th',
    frets: [-1, 5, 4, 5, 5, 5],
    fingers: [0, 2, 1, 3, 3, 3],
    baseFret: 4,
    rootString: 5,
    rootNoteString: 1,
  },

  // ========================
  // MOVABLE 11TH CHORDS
  // ========================
  {
    id: 'mov-a11',
    name: 'A 11th',
    symbol: 'A11',
    category: 'movable',
    type: '11th',
    frets: [5, 5, 5, 6, 5, 5],
    fingers: [1, 1, 1, 2, 1, 1],
    baseFret: 5,
    rootString: 6,
    rootNoteString: 0,
  },
  {
    id: 'mov-d11',
    name: 'D 11th',
    symbol: 'D11',
    category: 'movable',
    type: '11th',
    frets: [-1, 5, 5, 5, 7, 5],
    fingers: [0, 1, 1, 1, 3, 1],
    baseFret: 5,
    rootString: 5,
    rootNoteString: 1,
  },
  {
    id: 'mov-g11',
    name: 'G 11th',
    symbol: 'G11',
    category: 'movable',
    type: '11th',
    frets: [3, 3, 3, 4, 3, 3],
    fingers: [1, 1, 1, 2, 1, 1],
    baseFret: 3,
    rootString: 6,
    rootNoteString: 0,
  },
  {
    id: 'mov-e11',
    name: 'E 11th',
    symbol: 'E11',
    category: 'movable',
    type: '11th',
    frets: [0, 2, 2, 2, 3, 0],
    fingers: [0, 1, 1, 1, 2, 0],
    baseFret: 1,
    rootString: 6,
    rootNoteString: 0,
  },

  // ========================
  // MOVABLE 13TH CHORDS
  // ========================
  {
    id: 'mov-a13',
    name: 'A 13th',
    symbol: 'A13',
    category: 'movable',
    type: '13th',
    frets: [5, 7, 5, 6, 7, 5],
    fingers: [1, 3, 1, 2, 4, 1],
    baseFret: 5,
    rootString: 6,
    rootNoteString: 0,
  },
  {
    id: 'mov-d13',
    name: 'D 13th',
    symbol: 'D13',
    category: 'movable',
    type: '13th',
    frets: [-1, 5, 4, 5, 5, 7],
    fingers: [0, 2, 1, 3, 3, 4],
    baseFret: 4,
    rootString: 5,
    rootNoteString: 1,
  },
  {
    id: 'mov-g13',
    name: 'G 13th',
    symbol: 'G13',
    category: 'movable',
    type: '13th',
    frets: [3, 5, 3, 4, 5, 3],
    fingers: [1, 3, 1, 2, 4, 1],
    baseFret: 3,
    rootString: 6,
    rootNoteString: 0,
  },
  {
    id: 'mov-e13',
    name: 'E 13th',
    symbol: 'E13',
    category: 'movable',
    type: '13th',
    frets: [0, 2, 0, 1, 2, 2],
    fingers: [0, 2, 0, 1, 3, 4],
    baseFret: 1,
    rootString: 6,
    rootNoteString: 0,
  },

  // ========================
  // MOVABLE AUGMENTED
  // ========================
  {
    id: 'mov-daug',
    name: 'D Augmented',
    symbol: 'D+',
    category: 'movable',
    type: 'augmented',
    frets: [-1, -1, 0, 3, 3, 2],
    fingers: [0, 0, 0, 2, 3, 1],
    baseFret: 1,
    rootString: 4,
    rootNoteString: 2,
  },
  {
    id: 'mov-aaug',
    name: 'A Augmented',
    symbol: 'A+',
    category: 'movable',
    type: 'augmented',
    frets: [-1, 0, 3, 2, 2, 1],
    fingers: [0, 0, 4, 2, 3, 1],
    baseFret: 1,
    rootString: 5,
    rootNoteString: 1,
  },

  // ========================
  // MOVABLE DIMINISHED
  // ========================
  {
    id: 'mov-cdim',
    name: 'C Diminished',
    symbol: 'C°',
    category: 'movable',
    type: 'diminished',
    frets: [-1, 3, 4, 5, 4, -1],
    fingers: [0, 1, 2, 4, 3, 0],
    baseFret: 3,
    rootString: 5,
    rootNoteString: 1,
  },
  {
    id: 'mov-adim',
    name: 'A Diminished',
    symbol: 'A°',
    category: 'movable',
    type: 'diminished',
    frets: [-1, 0, 1, 2, 1, -1],
    fingers: [0, 0, 1, 3, 2, 0],
    baseFret: 1,
    rootString: 5,
    rootNoteString: 1,
  },
  {
    id: 'mov-ddim',
    name: 'D Diminished',
    symbol: 'D°',
    category: 'movable',
    type: 'diminished',
    frets: [-1, -1, 0, 1, 0, 1],
    fingers: [0, 0, 0, 1, 0, 2],
    baseFret: 1,
    rootString: 4,
    rootNoteString: 2,
  },

  // ========================
  // MOVABLE SUSPENDED
  // ========================
  {
    id: 'mov-csus4',
    name: 'C Suspended 4th',
    symbol: 'Csus4',
    category: 'movable',
    type: 'suspended',
    frets: [-1, 3, 5, 5, 6, 3],
    fingers: [0, 1, 2, 3, 4, 1],
    baseFret: 3,
    rootString: 5,
    rootNoteString: 1,
  },
  {
    id: 'mov-gsus4',
    name: 'G Suspended 4th',
    symbol: 'Gsus4',
    category: 'movable',
    type: 'suspended',
    frets: [3, 5, 5, 5, 3, 3],
    fingers: [1, 2, 3, 4, 1, 1],
    baseFret: 3,
    rootString: 6,
    rootNoteString: 0,
  },

  // ========================
  // MOVABLE AUGMENTED 7TH
  // ========================
  {
    id: 'mov-d-aug7',
    name: 'D Augmented 7th',
    symbol: 'D+7',
    category: 'movable',
    type: 'aug7',
    frets: [-1, 5, 4, 5, 5, 6],
    fingers: [0, 2, 1, 3, 3, 4],
    baseFret: 4,
    rootString: 5,
    rootNoteString: 1,
  },
  {
    id: 'mov-g-aug7',
    name: 'G Augmented 7th (3rd pos)',
    symbol: 'G+7',
    category: 'movable',
    type: 'aug7',
    frets: [3, 2, 3, 0, 0, 3],
    fingers: [2, 1, 3, 0, 0, 4],
    baseFret: 1,
    rootString: 6,
    rootNoteString: 0,
  },

  // ========================
  // MOVABLE HALF DIMINISHED 7TH
  // ========================
  {
    id: 'mov-a-halfdim7',
    name: 'A Half Diminished 7th',
    symbol: 'Am7b5',
    category: 'movable',
    type: 'halfDim7',
    frets: [5, -1, 5, 5, 4, -1],
    fingers: [2, 0, 3, 4, 1, 0],
    baseFret: 4,
    rootString: 6,
    rootNoteString: 0,
  },
  {
    id: 'mov-d-halfdim7',
    name: 'D Half Diminished 7th (5th pos)',
    symbol: 'Dm7b5',
    category: 'movable',
    type: 'halfDim7',
    frets: [-1, 5, 6, 5, 6, -1],
    fingers: [0, 1, 2, 1, 3, 0],
    baseFret: 5,
    rootString: 5,
    rootNoteString: 1,
  },
  {
    id: 'mov-g-halfdim7',
    name: 'G Half Diminished 7th',
    symbol: 'Gm7b5',
    category: 'movable',
    type: 'halfDim7',
    frets: [3, -1, 3, 3, 2, -1],
    fingers: [2, 0, 3, 4, 1, 0],
    baseFret: 2,
    rootString: 6,
    rootNoteString: 0,
  },

  // ========================
  // MOVABLE FULLY DIMINISHED 7TH
  // ========================
  {
    id: 'mov-c-dim7',
    name: 'C Fully Diminished 7th',
    symbol: 'Cdim7',
    category: 'movable',
    type: 'dim7',
    frets: [-1, 3, 4, 2, 4, 2],
    fingers: [0, 2, 3, 1, 4, 1],
    baseFret: 2,
    rootString: 5,
    rootNoteString: 1,
  },
  {
    id: 'mov-a-dim7',
    name: 'A Fully Diminished 7th',
    symbol: 'Adim7',
    category: 'movable',
    type: 'dim7',
    frets: [5, -1, 4, 5, 4, 5],
    fingers: [2, 0, 1, 3, 1, 4],
    baseFret: 4,
    rootString: 6,
    rootNoteString: 0,
  },
  {
    id: 'mov-d-dim7',
    name: 'D Fully Diminished 7th',
    symbol: 'Ddim7',
    category: 'movable',
    type: 'dim7',
    frets: [-1, 5, 6, 4, 6, 4],
    fingers: [0, 2, 3, 1, 4, 1],
    baseFret: 4,
    rootString: 5,
    rootNoteString: 1,
  },

  // ========================
  // MOVABLE SLASH
  // ========================
  {
    id: 'mov-e-gsharp',
    name: 'E over G#',
    symbol: 'E/G#',
    category: 'movable',
    type: 'slash',
    frets: [4, 2, 2, 1, 0, 0],
    fingers: [4, 2, 3, 1, 0, 0],
    baseFret: 1,
    rootString: 6,
    rootNoteString: 0,
  },
  {
    id: 'mov-a-csharp',
    name: 'A over C#',
    symbol: 'A/C#',
    category: 'movable',
    type: 'slash',
    frets: [-1, 4, 2, 2, 2, 0],
    fingers: [0, 4, 1, 2, 3, 0],
    baseFret: 1,
    rootString: 5,
    rootNoteString: 1,
  },
];
